<template>
  <v-tabs
    fixed-tabs
    background-color="#282348"
    dark
  >
    <v-tab>
      Inicio
    </v-tab>
    <v-tab>
      Servicios
    </v-tab>
    <v-tab>
      Acerca de Nosotros
    </v-tab>
    <v-tab>
      Contactanos
    </v-tab>
  </v-tabs>
</template>